apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: helloworld
spec:
  replicas: 6
  selector:
    matchLabels:
      app: helloworld
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      restartPolicy: Always
      containers:
      - name: helloworld
        image: 192.168.207.230:5000/helloworld:latest
        ports:
        - name: helloworld
          containerPort: 8080
      imagePullSecrets:
      - name: reghelloworld